"use client";
import { useState,type FormEvent } from "react";
import { useMutation } from "@tanstack/react-query";
import { bookingApi } from "@/services/booking-api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Card,CardContent } from "@/components/ui/card";
import { formatCurrency } from "@/lib/utils";
import type { Room } from "@/types/domain";
import { toast } from "@/components/ui/toast";

export function BookingLookup(){const [credentials,setCredentials]=useState({reference:"",email:""});const lookup=useMutation({mutationFn:()=>bookingApi.lookup(credentials.reference,credentials.email)});const cancel=useMutation({mutationFn:()=>bookingApi.guestCancel(credentials.reference,credentials.email),onSuccess:r=>{lookup.reset();toast.success(`Booking ${r.data.data.reference} cancelled`)},onError:()=>toast.error("This booking cannot be cancelled")});function submit(e:FormEvent){e.preventDefault();lookup.mutate()}const booking=lookup.data?.data.data;const room=booking&&typeof booking.room==="object"?(booking.room as Room).name:"";return <div className="grid gap-8 lg:grid-cols-[360px_1fr]"><form onSubmit={submit} className="h-fit rounded-2xl border bg-card p-6 shadow-soft"><h2 className="font-serif text-2xl text-primary">Find your reservation</h2><label className="mt-5 grid gap-2 text-sm font-semibold">Booking reference<Input required value={credentials.reference} onChange={e=>setCredentials({...credentials,reference:e.target.value.toUpperCase()})} placeholder="HMB-..."/></label><label className="mt-4 grid gap-2 text-sm font-semibold">Booking email<Input required type="email" value={credentials.email} onChange={e=>setCredentials({...credentials,email:e.target.value})}/></label><Button className="mt-5 w-full" disabled={lookup.isPending}>{lookup.isPending?"Searching…":"Find booking"}</Button>{lookup.isError&&<p className="mt-4 text-sm text-destructive">No booking matched those details.</p>}</form>{booking?<Card><CardContent className="p-7"><div className="flex items-center justify-between"><h2 className="font-serif text-3xl text-primary">{booking.reference}</h2><Badge variant="secondary">{booking.status.replaceAll("_"," ")}</Badge></div><dl className="mt-6 grid gap-5 sm:grid-cols-2"><div><dt className="text-xs uppercase text-muted-foreground">Room</dt><dd className="font-semibold">{room}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Guests</dt><dd className="font-semibold">{booking.guests}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Check-in</dt><dd className="font-semibold">{new Date(booking.checkIn).toLocaleDateString()}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Check-out</dt><dd className="font-semibold">{new Date(booking.checkOut).toLocaleDateString()}</dd></div><div><dt className="text-xs uppercase text-muted-foreground">Stay total</dt><dd className="font-semibold">{formatCurrency(booking.totalAmount)}</dd></div></dl>{!["CHECKED_IN","CHECKED_OUT","CANCELLED"].includes(booking.status)&&<Button className="mt-7" variant="outline" disabled={cancel.isPending} onClick={()=>cancel.mutate()}>Cancel booking</Button>}</CardContent></Card>:<div className="grid min-h-72 place-items-center rounded-2xl border border-dashed text-muted-foreground">Your booking details will appear here.</div>}</div>}
