"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Menu,Mountain,X } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { NotificationCenter } from "@/components/notifications/notification-center";
import { useCurrentUser } from "@/hooks/use-current-user";
import { cn } from "@/lib/utils";

const navigation=[{label:"Home",href:"/home"},{label:"Rooms",href:"/rooms"},{label:"Services",href:"/services"},{label:"My booking",href:"/my-booking"},{label:"About",href:"/about"},{label:"Gallery",href:"/gallery"},{label:"Contact",href:"/contact"}];
export function SiteHeader(){const [open,setOpen]=useState(false);const pathname=usePathname();const {data:user}=useCurrentUser();return <header className="relative z-40 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><Link href="/home" className="flex items-center gap-3 text-primary"><span className="grid size-10 place-items-center rounded-full border border-primary/20"><Mountain className="size-5"/></span><span><span className="block font-serif text-lg leading-none">Hotel Mount Bliss</span><span className="mt-1 block text-[9px] font-semibold uppercase tracking-[.28em] text-muted-foreground">Hospitality & comfort</span></span></Link><nav className="hidden items-center gap-7 lg:flex">{navigation.map(item=><Link key={item.href} href={item.href} className={cn("text-sm font-medium hover:text-primary",pathname===item.href?"text-primary":"text-muted-foreground")}>{item.label}</Link>)}</nav><div className="flex items-center gap-2">{user&&<><NotificationCenter/><Button asChild variant="outline" className="hidden sm:inline-flex"><Link href="/profile">My account</Link></Button></>}<Button asChild className="hidden xl:inline-flex"><Link href="/booking">Book now</Link></Button><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</Button></div></div>{open&&<nav className="absolute inset-x-0 top-full border-b bg-background p-5 shadow-xl lg:hidden"><div className="mx-auto grid max-w-7xl gap-1">{navigation.map(item=><Link key={item.href} href={item.href} onClick={()=>setOpen(false)} className="rounded-lg px-4 py-3 text-sm font-semibold hover:bg-secondary">{item.label}</Link>)}{user&&<Link href="/profile" onClick={()=>setOpen(false)} className="rounded-lg px-4 py-3 text-sm font-semibold hover:bg-secondary">My account</Link>}<Button asChild className="mt-2"><Link href="/booking">Book now</Link></Button></div></nav>}</header>}
